version: '3.9'
name: smart-juice-backend
services:
  api:
    container_name: smart-juice-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/smart_juice_db?schema=public
    volumes:
      - ./api:/app
      - /app/node_modules
  postgres:
    container_name: smart-juice-db
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart_juice_db

    ports:
      - '5432:5432'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
